name: Elixir CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - main


jobs:
  check:
    name: CI Checks
    strategy:
      matrix:
        cmd: [test, test.format, test.compile, test.build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            logflare-ex/deps
          key: mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: mix
      - run: mix deps.get
      - run: mix ${{ matrix.cmd }}

